name: Build Net Full Framework

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job_1:
   name: Build
   runs-on: [windows-latest]
   steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
    
    - name: Restore NuGet packages
      run: nuget restore ExemploGithubActionsNetFramework.sln

    - name: Build the Solution
      run: msbuild ExemploGithubActionsNetFramework.sln /p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:DisableAllVSGeneratedMSDeployParameter=true /p:SkipInvalidConfigurations=true 

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: exemploNetFrameworkArtifact
        path: D:\a\ExemploGithubActionsNetFramework\ExemploGithubActionsNetFramework\ExemploGithubActionsNetFramework\obj\Release\Package\ExemploGithubActionsNetFramework.zip
        
  job_2:  
    name: Deploy
    needs: job_1
    runs-on: [windows-latest] #aqui voce pode definir sua maquina self-hosted. Estou utilizando uma VM apenas para demonstração
    steps:
      - name: Download SegdocArtifact
        uses: actions/download-artifact@v2
        with:
          name: exemploNetFrameworkArtifact
          
        # Após o Download você pode implementar scripts de instalação e etc
        
  
